# Generated by Django 3.2.7 on 2022-04-06 20:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.forms.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aficiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcionAficiones', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.FloatField(default=0)),
                ('duracion_meses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('lugar', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('estudios', models.CharField(max_length=40)),
                ('piso_encontrado', models.BooleanField(default=False)),
                ('fecha_premium', models.DateTimeField(blank=True, default=None, null=True)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('foto', models.ImageField(upload_to='principal/static/images/users')),
                ('telefono', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+[1-9]\\d{1,14}$')])),
                ('sms_validado', models.BooleanField(default=False)),
                ('aficiones', models.ManyToManyField(to='principal.Aficiones')),
                ('piso', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.piso')),
                ('tags', models.ManyToManyField(to='principal.Tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='principal/static/images/pisos')),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.piso')),
            ],
        ),
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mate', models.BooleanField(default=django.forms.fields.NullBooleanField)),
                ('fecha_mate', models.DateTimeField(auto_now_add=True)),
                ('userEntrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to=settings.AUTH_USER_MODEL)),
                ('userSalida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userEntrada', 'userSalida')},
            },
        ),
    ]
