# Generated by Django 3.2.7 on 2022-03-23 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mates',
            name='userEntrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mates',
            name='userSalida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
