# Generated by Django 3.2.7 on 2022-04-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='publicKey',
            field=models.TextField(default='0J3RWk62hGhpwE5hPa-5YsZDldGxH3G_dsIu64BIUv0='),
        ),
    ]
