# Generated by Django 3.2.7 on 2022-04-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_publickey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='publicKey',
            field=models.TextField(default='HIMiBLB5ryxvxyfGd-mDofA5xdwcFe00UDZ6hYd0fkQ='),
        ),
    ]
