# Generated by Django 3.2.7 on 2022-03-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
